version: "3.7"

services:

  db:
    build: database
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    secrets:
      - db-password
    networks:
      - backnet
    environment:
      - MYSQL_DATABASE=db_main
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password

  redis:
    image: redis
    restart: always
    networks:
      - backnet
      
  web:
    build: .
    depends_on: 
      - db
      - redis
    restart: always
    ports:
      - "443:443"
    secrets:
      - db-password
    networks:
      - backnet
      - frontnet

secrets:
  db-password:
    file: database/password.txt

networks:
  backnet:
  frontnet: